# Site settings
title: We get signal
email: timido@domain.com
description: Notes about my digital experience
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: iosonogio
github_username:  iosonogio

# Build settings
markdown: kramdown

kramdown:
  input: GFM

permalink: /:categories/:title/
