# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title
relative_permalinks: false
encoding: utf-8

# Setup
title: "@iosonogio"
tagline: Notes on my digital experience
description: Notes on my digital experience
url: http://iosonogio.github.io
baseurl: ""
urlimg: https://iosonogio.github.io/img/

markdown: kramdown
kramdown:
  input: GFM

paginate: 3
paginate_path: "/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
timezone: Europe/Rome
future: true


## code highlight options
syntax_highlighter: rouge

gems:
  - jekyll-paginate

# About/contact
owner:
  name: iosonogio
  url: https://iosonogio.github.io
  avatar: foo.png
  #email:
  twitter: iosonogio
  linkedin:
  github:
  googleplus:

# Google Custom Search:
#google_search: xyz123abc

# Add disqus username for Disqus comment board:
disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc
